server:
  port: 8081

# Spring Security default user name and password
spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  profiles:
    active:

# INFO ENDPOINT CONFIGURATION
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

# SHUTDOWN ENDPOINT (ShutdownEndpoint)
management:
  endpoint:
    shutdown:
      enabled: true
    # HEALTH ENDPOINT
    health:
      show-details: always

  # ENDPOINTS WEB CONFIGURATION
  endpoints:
    web:
      exposure:
        include: "*"
