version: "2"
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile-prod
    image: thinhvn/sam-order:prod
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - 8081:8081
    restart: always