version: "2"
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile-dev
    image: thinhvn/sam-order:dev
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - 8081:8081
    restart: always